version: "3"

services:
  # PHP-Apache
  myapp-web:
    container_name: myapp-web
    # ./myapp-web/Dockerfile でイメージをビルド
    build:
      context: ./myapp-web
      dockerfile: Dockerfile
    # myapp-db 起動後に myapp-web を起動
    depends_on:
      - myapp-db
    # 80 番ポートを割り当て
    ports:
      - "80:80"
    # ローカル の html フォルダを
    # コンテナの /var/www/html にマウント
    volumes:
      - "../html:/var/www/html"

  # MySQL
  myapp-db:
    container_name: myapp-db
    image: mysql:8.0
    volumes:
      - "./initdb:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_DATABASE: sampledb
      MYSQL_USER: sample
      MYSQL_PASSWORD: pw
      MYSQL_ROOT_PASSWORD: passwd
    ports:
      - "3307:3306"

  # phpMyAdmin
  myapp-pma:
    container_name: myapp-pma
    image: phpmyadmin/phpmyadmin:5.0
    depends_on:
      - myapp-db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: myapp-db
      PMA_USER: root
      PMA_PASSWORD: passwd
